# Generated by Django 4.1.5 on 2023-01-29 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_active',
        ),
    ]
